name: track_it
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=2.19.6 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    go_router: ^6.5.5
    google_fonts: ^4.0.3
    equatable: ^2.0.5
    formz: ^0.6.0
    get: ^4.6.5
    provider: ^6.0.5
    meta: ^1.8.0
    async: ^2.10.0
    http: ^0.13.5

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0
    mockito: ^5.4.0
    build_runner: ^2.3.3
    test: ^1.22.0
    faker: ^2.1.0

flutter:

    uses-material-design: true
